config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.simple_captcha '/simple_captcha/:action', :controller => 'simple_captcha'
  map.manager "manager", :controller => "user_sessions", :action => "new"
  
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
  map.profile "profile", :controller => "users", :action => "edit"
  map.resources :user_sessions
  map.resources :users
  
  

  

  map.connect "/", :controller => "catalog", :action => "index", :language => "ru"
  map.connect "ru", :controller => "catalog", :action => "index", :language => "ru"
  map.connect "en", :controller => "catalog", :action => "index", :language => "en"
  
  map.connect ":language/p/:id", :controller => "p", :action => "index"
  map.connect ":language/news/:year/:month/:date/:id", :controller => "news", :action => "show"
  map.connect ":language/news", :controller => "news", :action => "index"

  map.connect "/p/:id", :controller => "p", :action => "index", :language => "ru"
  map.connect "/news/:year/:month/:date/:id", :controller => "news", :action => "show", :language => "ru"
  map.connect "/news", :controller => "news", :action => "index", :language => "ru"
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'

  map.connect 'robots.txt', :controller => "sitemap", :action => "robots"
  map.connect ':language/:controller/:action/:id'
  map.connect ':language/:controller/:action/:id.:format'

end

app/models/product.rb
class Product < ActiveRecord::Base
  xss_terminate :except => [:body, :body_en, :description, :description_en]

  has_and_belongs_to_many :fs



  before_save :set_titles
  def set_titles
    self.title = self.name if self.title.blank?
    self.title_en = self.name_en if self.title_en.blank?
  end


  def price_rub
    (((self.price.to_f * Option.get("kurs_usd").to_f / 100).to_f.ceil)*100).to_i
  end

  #п~_п╬я~Aя~Bя~@п╟пҐп╦я~GпҐп╟я~O пҐп╟п╡п╦пЁп╟я~Fп╦я~O
  def self.items_page(page , cond = '', per_page = 50, order = 'id DESC')
    if cond == ""
      cond = "is_service = 0"
    end
    paginate :per_page => per_page, :page => page,
      :conditions => cond,
      :order => order
  end

  def self.search_page(page, q, per_page, order)
    cond = ["(active = 1) AND (is_service = 0) AND ((name LIKE ?) OR (name_en LIKE ?) OR (meta_keywords LIKE ?) OR (meta_keywords_en LIKE ?))", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%"]
    return paginate :per_page => per_page, :page => page,
      :conditions => cond,
      :order => order
  end
  
  def self.filter_page(page, filter_ids, price=nil, currency="usd", per_page = 50, order = 'id DESC')
    if price.blank?
      cond = "is_service = 0"
    else
      if !currency.blank? && currency=="rub"
        price = price.to_f / Option.get("kurs_usd").to_f      
      end
      cond = ["(is_service = 0) AND (price <= ?) AND (price > 0)", price]
    end

    if filter_ids.blank?
      return paginate :per_page => per_page, :page => page,
        :conditions => cond,
        :order => order
    else

      return paginate :per_page => per_page, :page => page,
        :conditions => cond,
        :joins => "INNER JOIN fs_products ON (fs_products.f_id IN (#{filter_ids.join(',')})) AND (fs_products.product_id=products.id)",
        :order => order
    end
  end
  
  def self.category_page(page , cond='is_service = 0', category_id = '', per_page = 50, order = 'id DESC')
    if category_id == ''
      return paginate :per_page => per_page, :page => page,
        :conditions => cond,
        :order => order
    else
      return paginate :per_page => per_page, :page => page,
        :conditions => cond,
        :joins => "INNER JOIN categories_products ON (categories_products.category_id=#{category_id}) AND (categories_products.product_id=products.id)",
        :order => order
    end
  end

  has_many :images, :as => :image_owner, :order => :p, :dependent => :destroy
  def image
      img = Image.find(:first, :conditions => ["image_owner_id = ? AND image_owner_type = ?", self.id, self.type.to_s], :order => "p")
      if !img.blank?
        return img.image
      end
  end

  #has_and_belongs_to_many :categories, :class_name => "Category"
  has_and_belongs_to_many :categories
end

app/controllers/admin_products_controller.rb
include ApplicationHelper

class AdminProductsController < ApplicationController
  layout "admin"
  cache_sweeper :product_sweeper#, :only => [:set_parent, :sort, :delete, :new, :]

  before_filter :init_tabs
  
  include Admin
  
  
  
  def update_filter_value
    filter = F.find_by_id(params[:id])
    if !filter.blank?
      filter.value = params[:update_value]
      filter.save
    end
    render :text => params[:update_value]
  end
  
  def delete_filter_value
    filter = F.find_by_id(params[:id])
    if !filter.blank?
      filter.destroy
    end
    render :text => "$('#item_#{params[:id]}').remove();"
  end
  
  def sort_filter_values
    p = 0
    for filter_id in params[:item]
      filter = F.find_by_id(filter_id)
      if !filter.blank?
        filter.p = p
        filter.save
      end
      p = p + 1
    end
    render :text => "sorted"
  end
  
  def add_filter_value
    filter = F.new(params[:filter])
    if filter.save
      flash[:notice] = "Значение добавлено"
    end
    redirect_tab "/#{params[:controller]}/filters"
  end
  
  def filters
    @page_title = "Значения фильтров"  
  end
  
  def save_product_filters
    @item.fs = []
    for filter in @filters_titles
      #puts "filter: #{filter[:name]}"
      if (!params[:filters].blank?) && (!params[:filters][filter[:name]].blank?)
        for filter_id in params[:filters][filter[:name]]
          #puts "params[:filters][#{filter[:name]}] = #{params[:filters][filter[:name]]}"
          f = F.find_by_id(filter_id)
          if !f.blank?
            #puts "add..."
            @item.fs << f
          end
        end
      end
    end
    @item.save
  end
  

  def edit_filter
    @page_title = "Редактировать фильтр"
    @item = F.find_by_id(params[:id])
    if @item.blank?
      flash[:error] = "Не удалось найти фильтр"
      redirect_to "/admin_#{model_controller}/filters"
    else
      if request.post?
        if @item.update_attributes(params[:item])
          #save_product_filters
          flash[:notice] = "Запись отредактирована"
          redirect_to "/admin_#{model_controller}/edit_filter/#{@item.id}"
        end
      end
    end
  end

  def edit
    @page_title = "Редактировать #{model_title[:what]}"  
    @item = model_name.find_by_id(params[:id])
    if @item.blank?
      flash[:error] = "Не удалось найти #{model_title[:one]}"
      redirect_to "/admin_#{model_controller}/list"
    else
      if request.post?
        if @item.update_attributes(params[:item])
          #save_product_filters
          flash[:notice] = "Запись отредактирована"
          redirect_to "/admin_#{model_controller}/edit/#{@item.id}"
        end
      end
    end
  end
  
  def init_tabs
    @tabs = [["Добавить #{model_title[:what]}", "/#{params[:controller]}/new/#{params[:id]}"], ["Список #{model_title[:list]}", "/#{params[:controller]}/list/#{params[:id]}"], ["Список дополнительных услуг", "/#{params[:controller]}/services"], ["Настройка фильтров", "/#{params[:controller]}/filters"]]
    if params[:action] == "edit"
      @tabs = [["Редактировать #{model_title[:what]}", "/#{params[:controller]}/edit/#{params[:id]}"]] + @tabs
    end
  end
  
  def new_service
    if request.post?
      item = Product.new(params[:item])
      item.is_service = true
      if item.save
        flash[:notice] = "Дополнительная услуга добавлена."
      end
    end
    redirect_to "/#{params[:controller]}/services"
  end
  
  def services
    @page_title = "Список дополнительных услуг"  
    @items = Product.find(:all, :conditions => ["is_service = 1"], :order => "p")
  end
  
  def model_name
    Product
  end
  
  helper_method :model_title
  
  def model_title
    {:many => "товаров", :one => "товар", :what => "товар", :list => "товаров"}
  end
  
  
  
  def list
    @page_title = "Список #{model_title[:list]}"
    cond = ""
    #if !params.blank?
     if params[:category].to_s!=""
       @items = model_name.category_page(params[:page], 'is_service = 0', params[:category].to_i, 50, get_sort)
     else
       @items = model_name.items_page(params[:page], '', 50, get_sort)
     end    
  end
 end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/views/admin_products/_filter.html.erb
	<%admin_tab title do%>
		<%if !["price", "price_usd"].include?(name)%>
		<small>Разделяйте значение на русском|английском знком <b>|</b>, например: <b>красный|red</b></small>
		<%end%>
		<br><%form_tag "/#{params[:controller]}/add_filter_value" do%>
			<input type="hidden" name="filter[language]" value="ru"/>
			<input type="hidden" name="filter[name]" value="<%=name%>"/>
			<input name="filter[value]"/><%=submit_tag "Добавить значение"%>
			<input type="hidden" name="tab_selected" class="tab_selected" value="<%=@admin_tab_current%>"/>
		<%end%><br>
		<%sortable "/#{params[:controller]}/sort_filter_values?name=#{name}" do%>
			<%for filter in F.list(name) do%>
				<%sortable_item filter do %>
				<div itemid="<%=filter.id%>" style="float:left;" class="filter_value">
				<%=filter.value%>
				</div>
				<div style="float:right;">
				<a href="/admin_products/edit_filter/<%=filter.id%>">Редактировать</a>
				<a href="#" class="delete_filter" itemid="<%=filter.id%>">Удалить</a>
				</div>
				<%end%>
			<%end%>
		<%end%>		
	<%end%>

app/views/admin_products/_form.html.erb
<% form_tag "", :multipart => true do %>
	  <table width=100%  class="list">
	  	<tr><td>Включен</td><td><%=select :item, :active, [["Да", true], ["Нет", false]]%></td></tr>
		<tr><td nowrap>Название(рус.):</td><td><%= text_field :item, :name%></td><td>Название(англ.)</td><td><%=text_field :item, :name_en%></td></tr>
		<tr><td nowrap>Заголовок страницы(рус.):</td><td><%= text_field :item, :title%></td><td>Заголовок страницы(англ.)</td><td><%=text_field :item, :title_en%></td></tr>

		<tr><td>Артикул:</td><td><%= text_field :item, :article%></td></tr>
		<tr><td>Цена:</td><td><%= text_field :item, :price%></td></tr>
		<tr><td>Старая цена (перечеркнута):</td><td><%= text_field :item, :old_price%></td></tr>
		<tr><td>Добавить товар на витрину:</td><td><%= check_box :item, :is_special%></td></tr>
		<tr><td>Добавить товар в "приятные мелочи":</td><td><%= check_box :item, :is_cartspecial%></td></tr>
		<tr>
			<td>Товар не может заказываться самостоятельно</td>
			<td><%=check_box :item, :no_order_alone%></td>
		</tr>
		<tr><td>Количество в упаковке:</td><td><%= text_field :item, :count_in_pack%></td></tr>
		<tr><td>Количество на складе:</td><td><%= text_field :item, :count_on_stock%></td></tr>
		<tr>
			<td>Фото:</td>
			<td>
				<%if params[:action]=="edit"%>
				<a class="fancybox_big" href="/<%=params[:controller]%>/product_images/<%=@item.id%>" title="Фотографии #<%=h @item.name%>"><img id="product_image_<%=@item.id%>" alt="Фото (нажмите для редактирования)" title="Фото (Нажмите для редактирования)" src="<%=product_image(@item)%>" /></a>
				<br><small>Нажмите на фото, для редактирования списка фотографий.</small>
				<%end%>
				<%if params[:action]=="new"%>
				<%=file_field :product_image, :image%>
				<%end%>
			</td>
		</tr>
		<%=edit_meta_ru_en%>
		<tr>
			<td>Категория</td>
			<td class="category">
<%# collection_select(:item, :category_ids, Category.find(:all, :order => "category_id, p"), :id, :name,{},{:multiple => true, :name=>'item[category_ids][]'}) %>
<%= category_multi_select(:item, :category_ids, @item.categories)%>
			</td>
		</tr>
		<!--Filters-->
		<%for filter in @filters_titles%>
		<tr>
			<td><%=filter[:title]%></td>
			<td>
			<%for f in F.list(filter[:name])%>	
				<%=check_box_tag "item[f_ids][]", f.id, @item.fs.include?(f)%> <%=f.value%><br/>
			<%end%>
			</td>
		</tr>
		<%end%>
		<!--/Filters-->


       </table>
	  <br>
   Краткое Описание(рус.):<br>
<%=text_area :item, :description, :cols => 50, :rows => 3%><Br>
   Краткое Описание(англ.):<br>
<%=text_area :item, :description_en, :cols => 50, :rows => 3%><Br>
   Полное описание(рус.):<br>
<%=ckeditor_textarea :item, :body, :toolbar=>'Full', :width=>'800px', :heigth=>'200px' %>
   Полное описание(англ.):<br>
<%=ckeditor_textarea :item, :body_en, :toolbar=>'Full', :width=>'800px', :heigth=>'200px' %>
		<%if params[:action]=="new"%><%=submit_tag "Добавить"%><%end%>
		<%if params[:action]=="edit"%><%=submit_tag "Редактировать"%><%end%>

<% end %>

<script>
	$(document).ready(function(){
/*		$('td.category>select>option').click(function(){
			alert($(this).attr('selected'));
			if($(this).attr('selected')){
				$(this).attr('selected', true);
			}
			else{
				$(this).attr('selected', false);				
			};
		});*/
	});
</script>

app/views/admin_products/edit.html.erb
<% admin_page @tabs do%>
<%=render :partial => "form"%>
<% end %>

app/views/admin_products/edit_filter.html.erb
<% admin_page @tabs do%>
<% form_tag "", :multipart => true do %>
	  <table width=100%  class="list">
		<tr><td nowrap>Название(рус|англ):</td><td><%= text_field :item, :value%></td></tr>


		<tr><td nowrap>Заголовок(рус):</td><td><%= text_field :item, :title%></td><td>(англ.)</td><td><%=text_field :item, :title_en%></td></tr>


		<%=edit_meta_ru_en%>


       </table>
	  <br>
   Полное описание(рус.):<br>
<%=ckeditor_textarea :item, :body, :toolbar=>'Full', :width=>'800px', :heigth=>'200px' %>
   Полное описание(англ.):<br>
<%=ckeditor_textarea :item, :body_en, :toolbar=>'Full', :width=>'800px', :heigth=>'200px' %>
	<%=submit_tag "Редактировать"%>

<% end %>


<% end %>

app/views/admin_products/filters.html.erb
<%admin_page @tabs do%>
	<%=admin_tabs ["Повод", "Праздники", "Кому", "Цвет", "Цена(RUB)", "Цена(USD)"]%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "reason", :title => "Повод"}%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "holiday", :title => "Праздники"}%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "who", :title => "Кому"}%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "color", :title => "Цвет"}%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "price", :title => "Цена(RUB)"}%>
	<%=render :partial => "admin_products/filter", :locals => {:name => "price_usd", :title => "Цена(USD)"}%>
<%end%>
<script>
	$(document).ready(function(){
		$('.delete_filter').click(function(){
			if(confirm('Вы действительно хотите удалить значение?')){
				$(this).html('Удаляется...');
				$.ajax({
					url: '/<%=params[:controller]%>/delete_filter_value/'+$(this).attr('itemid'),
					dataType: 'script'
				});
			};
		});
		$('.filter_value').each(function(){
			$(this).editInPlace({
				saving_text: saving_text,
				cancel_button: cancel_button,
				save_button: save_button,
				default_text: default_text,
        		url: '/<%=params[:controller]%>/update_filter_value/'+$(this).attr('itemid'),
				params: 'field=value&authenticity_token=' + window._token,
        		show_buttons: true//,
				//success: inplaceEditorCallback
    		});			
		});		
	});
</script>

app/views/admin_products/list.html.erb
<%admin_page @tabs do%>
	<%=print_way @way,false%>
	<br><small>Кликните по названию/фотографии/цене/количеству чтобы изменить их.</small>

<form>
<b>Фильтр:</b> <%=category_filter(Category.find(:all, :conditions => "category_id = 0"), "category", params[:category])%>

<input type="submit" value="Фильтр"/>

</form>
	<%table_with_sort_links [["#", "id"], ["Вкл", "active"], ["Артикул", "article"], "Фото", ["Название", "name"], "Категории", ["Цена", "price"], "Старая цена", "В упаковке", "На складе", "Ред.", "Уд."], {:del_url => "/#{params[:controller]}/delete/", :item_name => model_title[:one], :update_url => "/#{params[:controller]}/update/"} do%>
		<%for item in @items%>
			<%tr item do%>
			<td><%=item.id%></td>
			<td class="edit_yesno" field="active"><%=show_yesno item.active%></td>
			<td class="edit_string" field="article"><%=item.article%></td>
			<td>
							<a class="fancybox_big" href="/<%=params[:controller]%>/product_images/<%=item.id%>" title="Фотографии #<%=h item.name%>"><img id="product_image_<%=item.id%>" alt="Фото (нажмите для редактирования)" title="Фото (Нажмите для редактирования)" src="<%=product_image(item)%>" /></a>
			</td>
			<td class="edit_string" field="name"><%=item.name%></td>
			<td><%=item.categories.map{|i| i.name}.join(", ")%></td>
			<td class="edit_string" field="price"><%=item.price%></td>
			<td class="edit_string" field="old_price"><%=item.old_price%></td>
			<td class="edit_string" field="count_in_pack"><%=item.count_in_pack%></td>
			<td class="edit_string" field="count_on_stock"><%=item.count_on_stock%></td>
			<td><%=btn_edit item%></td>
			<td><%=btn_del%></td>
			<%end%>
		<%end%>
	<%end%>
	<%=will_paginate @items%>
<%end%>

app/views/admin_products/new.html.erb
<% admin_page @tabs do%>
<%=render :partial => "form"%>
<% end %>

app/views/admin_products/services.html.erb
<style>
li.ui-state-default {
/*	height: 30px;*/
}
.sortable {
	width: 100%;
}
</style>
<%admin_page @tabs do%>
	<%quick_add "Добавить дополнительную услугу", "/#{params[:controller]}/new_service" do%>
	<table>
		<tr>
			<td>Название</td>
			<td><input name="item[name]"></td>
		</tr>
		<tr>
			<td>Цена</td>
			<td><input name="item[price]"></td>
		</tr>
		<tr>
			<td>Товар не может заказываться самостоятельно</td>
			<td><input value="1" name="item[no_order_alone]" type="checkbox" checked="checked"/></td>
		</tr>
	</table>
	<%end%>
	<br><Br>
	<small>
		Вы можете изменить порядок расположения дополнительных услуг с помощью перетягивания мышью.
		<br>
		Нажмите на название/цену, чтобы изменить их.
		<br>
		<%=help_translate%>
	</small>
	<Table style="padding-left: 30px;">
		<tr>
			<td width="350"><b>Название</b></td>
			<td width="350"><b>Название(англ)</b></td>
			<td width="150"><b>Товар не может заказываться самостоятельно</b></td>
			<td><b>Цена</b></td>
		</tr>
	</Table>
	<%sortable "/#{params[:controller]}/sort" do %>
		<%for item in @items%>
			<%sortable_item item do%>
				<div style="float:left;">
					<table cellpadding="0" cellspacing="0" class="product_info" update_url="/<%=params[:controller]%>/update/">
					<tbody>
						<tr rowid="<%=item.id%>">
							<td width="350" class="edit_string" field="name"><%=item.name%></td><td></td>
							<td width="350" class="edit_string" field="name_en"><%=item.name_en%></td>
							<td width="150">
<input class="update_no_order_alone" type="checkbox" item_id="<%=item.id%>" <%if item.no_order_alone%>checked='checked'<%end%> />
							</td>
							<td class="edit_string" field="price"><%=item.price%></td><td>$</td>
						</tr>
					</tbody>
					</table>
				</div>
				<div class="ctrls" style="float:right;">
<!--							<a href="/<%=params[:controller]%>/edit/<%=item.id%>" style='color:blue;font-size:12px;text-decoration: underline;'>Редактировать <%=model_title[:what]%></a>
							<br/>-->
							<a href="" item_id="<%=item.id%>" class="del_product" style='color:blue;font-size:12px;text-decoration: underline;'>Удалить</a>
				</div>
			<%end%>
		<%end%>
	<%end%>
<%end%>

<script>
	$(document).ready(function(){
		$('.update_no_order_alone').click(function(){
			$(this).after('<img src="/images/ajax/load/1.gif" style="vertical-align: middle;" class="loader"/>')
			if($(this).is(':checked')){
				v = '1';
			}else{
				v = '0';
			};
			$.ajax({
				el: $(this),
				url: '/admin_products/update/' + $(this).attr('item_id') + '?field=no_order_alone&update_value=' + v,
				success: function(){
					if(this.el.next().is('.loader')){
						this.el.next().remove();
					};
				}
			});
		});

		$('.del_product').click(function(){
			if(confirm('Вы действительно хотите удалить услугу?'))	
			{
				item_id = $(this).attr('item_id');
//				$("#item_" + item_id).effect("drop",{},500);
//				$("#drop_" + item_id).hide("drop", { direction: "down" }, 1000);
				
				$(this).html("Идёт удаление...")
				$.ajax({
					"item_id": $(this).attr('item_id'),
					"type": "GET",
					"url": "/<%=params[:controller]%>/delete/" + $(this).attr('item_id'),
					"success": function(){
						$('#item_' + this.item_id).remove();
					}
				})
			};
			return false;
		})
	});
</script>